version: "2"
services:

  jenkins:
    image: jenkins-withdocker
#    ports:
#    - "8080:8080"
    volumes:
    - "/home/salvatore/jenkins/jenkins_home:/var/jenkins_home"
    - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
    - JENKINS_OPTS="--prefix=/jenkins"

